on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: sudo npm i -g aws-cdk@1.96.0
      - run: npm i
      - run: make lint && make build

      - name: cdk diff
        run: make diff

      - name: cdk deploy
        run: make deploy
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
